# Generated by Django 5.1.1 on 2025-01-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_iphones_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iphones',
            old_name='price',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='iphones',
            name='desc',
        ),
    ]
